name: Basic Workflow

on:
    push:
        branches: feature/basic-workflow

jobs:
    do-things:
        name: Do Things
        runs-on: ubuntu-22.04
        steps:
            - name: The Thing I've Done
              run: echo "I've done a thing!"
