name: Basic Workflow

on:
    workflow_dispatch:

jobs:
    do-things:
        name: Do Things
        runs-on: ubuntu-22.04
        steps:
            - name: The Thing I've Done
              run: echo "I've done a thing!"

            - name: An Error I made
              run: |
                echo "I've made an Error"
                exit 1