name: Continuous Integration & Delivery

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: mkdir golang_app
        working-directory: golang_app

    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3.1.0

      - name: Get Dependencies
        run: go get app

      - name: Build
        run: go build

      - name: Run Linting
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: golang_app

      - name: Run Tests
        run: go test