name: Concurrent Workflows
on:
  push:
    branches: [main]
    
jobs:
  do-things:
    name: Do Things With Concurrency
    runs-on: ubuntu-latest
    concurrency: 
      group: static-group
    steps:
      - name: The Thing I've Done
        run: echo "I've done a thing!"; sleep 15;