name: Issue Event
on:
    issues:
        types: [opened]

jobs:
    doing-more-things:
        name: Doing Things from Issues
        runs-on: ubuntu-latest
        steps:
            - name: Output Issue Info
              env:
                  EVENT_NAME: ${{ github.event_name }}
                  EVENT_ACTION: ${{ github.event.action }}
              run: echo " The actions '${EVENT_ACTIONS}' was performed against '${EVENT_NAME}'"
