name: Using Shared Workflow
on:
  workflow_dispatch:
    
jobs:
  centralized-job:
    uses: ./.github/workflows/manual.yaml
    with:
      choice-example: debug
      string-example: a thing

# Notes
# When using a shared workflow from a public or internal repository, the syntax will be slightly different: <owner>/<repo>/<path-to-workflow>@<release-tag>
# Workflows shared from an internal repository must have the appropriate repository settings (see instructions here)